In [ ]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import statsmodels.api as sm

In [8]:
# Loding the TO csv file
df1 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/TO_test/Final/Test_100/cyl0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/TO_test/Final/Test_75/cyl0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/TO_test/Final/Test_50/cyl0.csv")


# Concatenating the 10 csv files
df = pd.concat([df1, df2, df3])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32264.6,32529.0,2.274062e+12,4.072355,140.0,2.853564,32762.0,81.849881,32394.368251,32397.0,...,74.678801,0.006375,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32270.0,32534.4,1.067532e+12,4.067255,141.0,2.835917,32703.0,81.601419,32398.719764,32400.0,...,89.618349,0.006093,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32273.8,32538.4,3.600111e+11,4.049429,148.5,2.827263,32654.0,85.060392,32397.285714,32398.0,...,85.253916,0.015948,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [10]:
# Loding the GE csv files and joining them in a single dataframe
df1 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/GE_test/Final/Test_100/cyl0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/GE_test/Final/Test_75/cyl0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/GE_test/Final/Test_50/cyl0.csv")


df = pd.concat([df1, df2, df3])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33277.0,33546.0,2.542153e+12,4.120867,143.0,2.920226,33755.0,84.280220,33413.127800,33415.0,...,82.866634,0.004858,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33286.0,33551.8,1.164882e+12,4.111297,143.5,2.844934,33722.0,84.745166,33419.241611,33418.0,...,79.918179,0.006443,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33282.0,33562.6,4.526213e+11,4.108231,142.0,2.731653,33707.0,86.096132,33430.103704,33428.0,...,67.492707,0.010360,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1

In [11]:
#Save the dataframe in a csv file
df_TO.to_csv('../../../../RadiomiK/Features_Volume_test/TO_test/Final/Global/cyl0_glob.csv', index=False)
df_GE.to_csv('../../../../RadiomiK/Features_Volume_test/GE_test/Final/Global/cyl0_glob.csv', index=False)

In [12]:
#add a column to the dataframe with the number of test that goes from 1 to 3
df_TO.insert(0, 'Test', range(1, 1 + len(df_TO)))
df_GE.insert(0, 'Test', range(1, 1 + len(df_GE)))

df_TO

,Test,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,1,32264.6,32529.0,2.274062e+12,4.072355,140.0,2.853564,32762.0,81.849881,32394.368251,...,74.678801,0.006375,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,2,32270.0,32534.4,1.067532e+12,4.067255,141.0,2.835917,32703.0,81.601419,32398.719764,...,89.618349,0.006093,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,3,32273.8,32538.4,3.600111e+11,4.049429,148.5,2.827263,32654.0,85.060392,32397.285714,...,85.253916,0.015948,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [13]:
#Keep only the [1,87] columns of the dataframe
df_TO = df_TO.iloc[:, 1:87]
df_GE = df_GE.iloc[:, 1:87]

df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis
0,32264.6,32529.0,2.274062e+12,4.072355,140.0,2.853564,32762.0,81.849881,32394.368251,32397.0,...,148.803415,16.842875,193.535302,7.785418,1472.268113,0.054921,0.010744,0.375192,74.678801,0.006375
0,32270.0,32534.4,1.067532e+12,4.067255,141.0,2.835917,32703.0,81.601419,32398.719764,32400.0,...,70.533923,16.864103,198.093412,7.281219,1388.793510,0.050049,0.009882,0.436572,89.618349,0.006093
0,32273.8,32538.4,3.600111e+11,4.049429,148.5,2.827263,32654.0,85.060392,32397.285714,32398.0,...,24.755102,17.826246,172.513120,6.026239,983.142857,0.059035,0.019911,0.488638,85.253916,0.015948

In [14]:
#calculate the CV of each feature
cv_TO = df_TO.std() / df_TO.mean()
cv_GE = df_GE.std() / df_GE.mean()

#Create a dataframe with the CV of each feature with the name of the column "CV"
cv_TO = pd.DataFrame(cv_TO, columns=['CV'])
cv_GE = pd.DataFrame(cv_GE, columns=['CV'])

#add column with the name of the feature
cv_TO['Feature'] = cv_TO.index
cv_GE['Feature'] = cv_GE.index

#change the index of the dataframe
cv_TO = cv_TO.reset_index(drop=True)
cv_GE = cv_GE.reset_index(drop=True)

#Add a column Manufacturer with the name of the manufacturer
cv_TO['Manufacturer'] = 'Toshiba'
cv_GE['Manufacturer'] = 'GE'

#concatenate the two dataframe
cv = pd.concat([cv_TO, cv_GE])

#reset the index
cv = cv.reset_index(drop=True)


cv

           CV                                            Feature Manufacturer
0    0.000143                   original_firstorder_10Percentile      Toshiba
1    0.000145                   original_firstorder_90Percentile      Toshiba
2    0.784367                         original_firstorder_Energy      Toshiba
3    0.002963                        original_firstorder_Entropy      Toshiba
4    0.032450             original_firstorder_InterquartileRange      Toshiba
..        ...                                                ...          ...
167  0.185297  original_gldm_LargeDependenceLowGrayLevelEmphasis           GE
168  0.346911                 original_gldm_LowGrayLevelEmphasis           GE
169  0.052956              original_gldm_SmallDependenceEmphasis           GE
170  0.106297  original_gldm_SmallDependenceHighGrayLevelEmph...           GE
171  0.392239  original_gldm_SmallDependenceLowGrayLevelEmphasis           GE

[172 rows x 3 columns]

In [15]:
#Get the features with CV > 0.10
cv_10 = cv[cv['CV'] > 0.10]

#reset the index
cv_10 = cv_10.reset_index(drop=True)

cv_10

          CV                                            Feature Manufacturer
0   0.784367                         original_firstorder_Energy      Toshiba
1   0.111101                          original_firstorder_Range      Toshiba
2   0.784367                    original_firstorder_TotalEnergy      Toshiba
3   0.185082                          original_glcm_JointEnergy      Toshiba
4   0.279732                                 original_glcm_Imc2      Toshiba
..       ...                                                ...          ...
62  0.275442  original_gldm_LargeDependenceHighGrayLevelEmph...           GE
63  0.185297  original_gldm_LargeDependenceLowGrayLevelEmphasis           GE
64  0.346911                 original_gldm_LowGrayLevelEmphasis           GE
65  0.106297  original_gldm_SmallDependenceHighGrayLevelEmph...           GE
66  0.392239  original_gldm_SmallDependenceLowGrayLevelEmphasis           GE

[67 rows x 3 columns]

In [11]:
#Save the dataframe in a csv file
cv_10.to_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_repeatable/cv_Cyl0.csv', index=False)