In [ ]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import statsmodels.api as sm

/Users/mariairenetenerani/anaconda3/envs/Apple_tensorflow_env/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.5.4.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

In [2]:
# Loding the TO csv file
df1 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/TO_test/Final/Test_100/rect0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/TO_test/Final/Test_75/rect0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/TO_test/Final/Test_50/rect0.csv")


# Concatenating the 10 csv files
df = pd.concat([df1, df2, df3])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31961.0,32680.5,2.943823e+12,5.448234,412.00,2.448626,33110.0,228.588345,32331.353693,32343.0,...,871.228089,0.001408,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31986.5,32680.5,1.355199e+12,5.407688,409.00,2.442607,33110.0,223.534184,32335.837191,32337.5,...,799.740291,0.001880,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31971.2,32681.0,4.684285e+11,5.380511,420.75,2.404864,32896.0,230.146684,32334.571429,32354.5,...,838.231326,0.003422,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [4]:
# Loding the GE csv files and joining them in a single dataframe
df1 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/GE_test/Final/Test_100/rect0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/GE_test/Final/Test_75/rect0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Volume_test/GE_test/Final/Test_50/rect0.csv")


df = pd.concat([df1, df2, df3])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32817.5,33891.0,3.248462e+12,5.683792,610.00,2.032641,34303.0,323.400087,33374.641289,33384.0,...,692.333150,0.023599,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32839.1,33893.0,1.528304e+12,5.704796,598.25,2.083662,34303.0,321.245660,33373.325802,33378.0,...,680.373102,0.026618,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32782.2,33891.5,5.568012e+11,5.553740,622.50,1.974179,34220.0,332.010560,33368.420000,33391.0,...,697.334639,0.034682,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1

In [5]:
#Save the dataframe in a csv file
df_TO.to_csv('../../../../RadiomiK/Features_Volume_test/TO_test/Final/Global/rect0_glob.csv', index=False)
df_GE.to_csv('../../../../RadiomiK/Features_Volume_test/GE_test/Final/Global/rect0_glob.csv', index=False)

In [6]:
#add a column to the dataframe with the number of test that goes from 1 to 3
df_TO.insert(0, 'Test', range(1, 1 + len(df_TO)))
df_GE.insert(0, 'Test', range(1, 1 + len(df_GE)))

df_TO

,Test,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,1,31961.0,32680.5,2.943823e+12,5.448234,412.00,2.448626,33110.0,228.588345,32331.353693,...,871.228089,0.001408,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,2,31986.5,32680.5,1.355199e+12,5.407688,409.00,2.442607,33110.0,223.534184,32335.837191,...,799.740291,0.001880,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,3,31971.2,32681.0,4.684285e+11,5.380511,420.75,2.404864,32896.0,230.146684,32334.571429,...,838.231326,0.003422,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [7]:
#Keep only the [1,87] columns of the dataframe
df_TO = df_TO.iloc[:, 1:87]
df_GE = df_GE.iloc[:, 1:87]

df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis
0,31961.0,32680.5,2.943823e+12,5.448234,412.00,2.448626,33110.0,228.588345,32331.353693,32343.0,...,72.072443,120.443360,1400.410866,3.297585,4906.328480,0.003667,0.001728,0.642353,871.228089,0.001408
0,31986.5,32680.5,1.355199e+12,5.407688,409.00,2.442607,33110.0,223.534184,32335.837191,32337.5,...,33.996914,114.817577,1267.881173,3.236111,4337.378086,0.004332,0.002219,0.652112,799.740291,0.001880
0,31971.2,32681.0,4.684285e+11,5.380511,420.75,2.404864,32896.0,230.146684,32334.571429,32354.5,...,11.986607,120.160590,1270.551339,3.017857,4054.002232,0.005712,0.003748,0.677386,838.231326,0.003422

In [9]:
#calculate the CV of each feature
cv_TO = df_TO.std() / df_TO.mean()
cv_GE = df_GE.std() / df_GE.mean()

#Create a dataframe with the CV of each feature with the name of the column "CV"
cv_TO = pd.DataFrame(cv_TO, columns=['CV'])
cv_GE = pd.DataFrame(cv_GE, columns=['CV'])

#add column with the name of the feature
cv_TO['Feature'] = cv_TO.index
cv_GE['Feature'] = cv_GE.index

#change the index of the dataframe
cv_TO = cv_TO.reset_index(drop=True)
cv_GE = cv_GE.reset_index(drop=True)

#Add a column Manufacturer with the name of the manufacturer
cv_TO['Manufacturer'] = 'Toshiba'
cv_GE['Manufacturer'] = 'GE'

#concatenate the two dataframe
cv = pd.concat([cv_TO, cv_GE])

#reset the index
cv = cv.reset_index(drop=True)


cv

           CV                                            Feature Manufacturer
0    0.000401                   original_firstorder_10Percentile      Toshiba
1    0.000009                   original_firstorder_90Percentile      Toshiba
2    0.789209                         original_firstorder_Energy      Toshiba
3    0.006297                        original_firstorder_Entropy      Toshiba
4    0.014749             original_firstorder_InterquartileRange      Toshiba
..        ...                                                ...          ...
167  0.120494  original_gldm_LargeDependenceLowGrayLevelEmphasis           GE
168  0.130593                 original_gldm_LowGrayLevelEmphasis           GE
169  0.030281              original_gldm_SmallDependenceEmphasis           GE
170  0.012631  original_gldm_SmallDependenceHighGrayLevelEmph...           GE
171  0.202479  original_gldm_SmallDependenceLowGrayLevelEmphasis           GE

[172 rows x 3 columns]

In [10]:
#Get the features with CV > 0.10
cv_10 = cv[cv['CV'] > 0.10]

#reset the index
cv_10 = cv_10.reset_index(drop=True)

cv_10

          CV                                            Feature Manufacturer
0   0.789209                         original_firstorder_Energy      Toshiba
1   0.789209                    original_firstorder_TotalEnergy      Toshiba
2   0.501884                          original_glcm_JointEnergy      Toshiba
3   0.118051                                 original_glcm_Imc2      Toshiba
4   0.510632                   original_glcm_MaximumProbability      Toshiba
5   0.771612              original_glrlm_GrayLevelNonUniformity      Toshiba
6   0.402331         original_glrlm_LongRunLowGrayLevelEmphasis      Toshiba
7   0.412695             original_glrlm_LowGrayLevelRunEmphasis      Toshiba
8   0.787125              original_glrlm_RunLengthNonUniformity      Toshiba
9   0.415284        original_glrlm_ShortRunLowGrayLevelEmphasis      Toshiba
10  0.756986              original_glszm_GrayLevelNonUniformity      Toshiba
11  0.106262      original_glszm_LargeAreaHighGrayLevelEmphasis      Toshiba
12  0.294662       original_glszm_LargeAreaLowGrayLevelEmphasis      Toshiba
13  0.434800            original_glszm_LowGrayLevelZoneEmphasis      Toshiba
14  0.758823               original_glszm_SizeZoneNonUniformity      Toshiba
15  0.462605       original_glszm_SmallAreaLowGrayLevelEmphasis      Toshiba
16  0.768095              original_gldm_DependenceNonUniformity      Toshiba
17  0.772483               original_gldm_GrayLevelNonUniformity      Toshiba
18  0.228202  original_gldm_LargeDependenceLowGrayLevelEmphasis      Toshiba
19  0.410743                 original_gldm_LowGrayLevelEmphasis      Toshiba
20  0.470909  original_gldm_SmallDependenceLowGrayLevelEmphasis      Toshiba
21  0.766695                         original_firstorder_Energy           GE
22  0.379056                       original_firstorder_Skewness           GE
23  0.766695                    original_firstorder_TotalEnergy           GE
24  0.106606                     original_firstorder_Uniformity           GE
25  0.189218                         original_glcm_ClusterShade           GE
26  0.480844                          original_glcm_Correlation           GE
27  0.503539                          original_glcm_JointEnergy           GE
28  0.199082                   original_glcm_MaximumProbability           GE
29  0.742932              original_glrlm_GrayLevelNonUniformity           GE
30  0.106170    original_glrlm_GrayLevelNonUniformityNormalized           GE
31  0.120128         original_glrlm_LongRunLowGrayLevelEmphasis           GE
32  0.134349             original_glrlm_LowGrayLevelRunEmphasis           GE
33  0.763684              original_glrlm_RunLengthNonUniformity           GE
34  0.110605                         original_glrlm_RunVariance           GE
35  0.138310        original_glrlm_ShortRunLowGrayLevelEmphasis           GE
36  0.717671              original_glszm_GrayLevelNonUniformity           GE
37  0.264483                   original_glszm_LargeAreaEmphasis           GE
38  0.525616       original_glszm_LargeAreaLowGrayLevelEmphasis           GE
39  0.231037            original_glszm_LowGrayLevelZoneEmphasis           GE
40  0.751112               original_glszm_SizeZoneNonUniformity           GE
41  0.238322       original_glszm_SmallAreaLowGrayLevelEmphasis           GE
42  0.548408                        original_glszm_ZoneVariance           GE
43  0.743396              original_gldm_DependenceNonUniformity           GE
44  0.145382                   original_gldm_DependenceVariance           GE
45  0.746839               original_gldm_GrayLevelNonUniformity           GE
46  0.120494  original_gldm_LargeDependenceLowGrayLevelEmphasis           GE
47  0.130593                 original_gldm_LowGrayLevelEmphasis           GE
48  0.202479  original_gldm_SmallDependenceLowGrayLevelEmphasis           GE

In [11]:
#Save the dataframe in a csv file
cv_10.to_csv('../../../../RadiomiK/Features_Volume_test/Features_Not_repeatable/cv_Rect0.csv', index=False)