In [ ]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import statsmodels.api as sm

In [13]:
# Loding the TO csv file
df1 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test1/cyl0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test2/cyl0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test3/cyl0.csv")
df4 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test4/cyl0.csv")
df5 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test5/cyl0.csv")
df6 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test6/cyl0.csv")
df7 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test7/cyl0.csv")
df8 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test8/cyl0.csv")
df9 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test9/cyl0.csv")
df10 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test10/cyl0.csv")

# Concatenating the 10 csv files
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32264.6,32529.0,2.274147e+12,4.074692,139.0,2.873650,32728.0,81.360987,32394.973235,32397.0,...,75.288279,0.006400,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32262.0,32529.0,2.273877e+12,4.083260,140.5,2.836964,32762.0,82.740461,32393.052607,32395.0,...,76.546463,0.006603,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32263.0,32529.0,2.273938e+12,4.088103,142.0,2.852911,32762.0,82.664610,32393.482695,32396.0,...,76.523969,0.006606,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32265.6,32527.4,2.273964e+12,4.069119,140.0,2.850971,32762.0,81.822975,32393.674665,32395.0,...,76.005966,0.006393,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32263.6,32530.0,2.274130e+12,4.076701,141.0,2.855036,32762.0,82.008632,32394.853715,32397.0,...,76.383426,0.006672,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32265.0,32525.0,2.273825e+12,4.058286,136.5,2.887308,32762.0,80.665350,32392.684818,32395.0,...,74.478313,0.005986,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32264.0,32530.0,2.274161e+12,4.079378,140.0,2.852640,32728.0,81.752489,32395.071066,32396.0,...,76.988267,0.006667,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32262.0,32525.4,2.273692e+12,4.072814,139.5,2.852978,32762.0,81.883404,32391.733272,32394.0,...,76.901289,0.006259,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32262.0,32530.0,2.273992e+12,4.090385,142.0,2.847930,32762.0,82.747473,32393.869866,32395.0,...,77.185143,0.006828,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,32265.6,32524.0,2.273763e+12,4.053863,136.5,2.893640,32762.0,80.478524,32392.242732,32394.0,...,75.895393,0.006009,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [14]:
# Loding the GE csv files and joining them in a single dataframe
df1 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test1/cyl0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test2/cyl0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test3/cyl0.csv")
df4 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test4/cyl0.csv")
df5 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test5/cyl0.csv")
df6 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test6/cyl0.csv")
df7 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test7/cyl0.csv")
df8 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test8/cyl0.csv")
df9 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test9/cyl0.csv")
df10 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test10/cyl0.csv")

df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,33278.0,33547.0,2.542216e+12,4.109955,142.0,2.905679,33755.0,83.848071,33413.543698,33415.0,...,82.436210,0.004561,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33274.0,33546.0,2.541904e+12,4.136828,144.0,2.925117,33755.0,85.467146,33411.488801,33413.0,...,94.317814,0.003731,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33278.0,33548.0,2.542341e+12,4.125819,145.0,2.888509,33769.0,85.020742,33414.361880,33416.0,...,83.634059,0.004602,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33275.6,33544.0,2.541931e+12,4.110997,141.0,2.957011,33755.0,83.617745,33411.675450,33414.0,...,81.684958,0.004782,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33277.0,33549.0,2.542475e+12,4.125807,142.0,2.882909,33755.0,84.663516,33415.244181,33416.0,...,83.668857,0.004333,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33274.6,33545.0,2.541926e+12,4.125833,143.0,2.935678,33755.0,84.627009,33411.638560,33413.0,...,82.857226,0.004978,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33278.0,33549.0,2.542516e+12,4.118896,142.0,2.872372,33755.0,84.367213,33415.516908,33417.0,...,83.761259,0.004137,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33271.0,33544.4,2.541584e+12,4.144232,147.0,2.931446,33755.0,85.966975,33409.381643,33410.0,...,94.001502,0.003811,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33278.0,33550.4,2.542611e+12,4.128765,144.0,2.853166,33769.0,85.257820,33416.134827,33417.0,...,84.953264,0.004078,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,33272.6,33543.0,2.541700e+12,4.121495,141.0,2.963273,33755.0,84.343134,33410.151076,33412.0,...,81.866756,0.004906,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1

In [15]:
#Save the dataframe in a csv file
df_TO.to_csv('../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Global/cyl0_glob.csv', index=False)
df_GE.to_csv('../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Global/cyl0_glob.csv', index=False)

In [16]:
#add a column to the dataframe with the number of test that goes from 1 to 10
df_TO.insert(0, 'Test', range(1, 1 + len(df_TO)))
df_GE.insert(0, 'Test', range(1, 1 + len(df_GE)))

df_TO

,Test,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,1,32264.6,32529.0,2.274147e+12,4.074692,139.0,2.873650,32728.0,81.360987,32394.973235,...,75.288279,0.006400,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,2,32262.0,32529.0,2.273877e+12,4.083260,140.5,2.836964,32762.0,82.740461,32393.052607,...,76.546463,0.006603,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,3,32263.0,32529.0,2.273938e+12,4.088103,142.0,2.852911,32762.0,82.664610,32393.482695,...,76.523969,0.006606,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,4,32265.6,32527.4,2.273964e+12,4.069119,140.0,2.850971,32762.0,81.822975,32393.674665,...,76.005966,0.006393,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,5,32263.6,32530.0,2.274130e+12,4.076701,141.0,2.855036,32762.0,82.008632,32394.853715,...,76.383426,0.006672,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,6,32265.0,32525.0,2.273825e+12,4.058286,136.5,2.887308,32762.0,80.665350,32392.684818,...,74.478313,0.005986,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,7,32264.0,32530.0,2.274161e+12,4.079378,140.0,2.852640,32728.0,81.752489,32395.071066,...,76.988267,0.006667,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,8,32262.0,32525.4,2.273692e+12,4.072814,139.5,2.852978,32762.0,81.883404,32391.733272,...,76.901289,0.006259,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,9,32262.0,32530.0,2.273992e+12,4.090385,142.0,2.847930,32762.0,82.747473,32393.869866,...,77.185143,0.006828,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,10,32265.6,32524.0,2.273763e+12,4.053863,136.5,2.893640,32762.0,80.478524,32392.242732,...,75.895393,0.006009,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [17]:
#Keep only the [1,87] columns of the dataframe
df_TO = df_TO.iloc[:, 1:87]
df_GE = df_GE.iloc[:, 1:87]

df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis
0,32264.6,32529.0,2.274147e+12,4.074692,139.0,2.873650,32728.0,81.360987,32394.973235,32397.0,...,149.236271,16.808627,194.188740,8.056760,1534.881864,0.055919,0.010713,0.378523,75.288279,0.006400
0,32262.0,32529.0,2.273877e+12,4.083260,140.5,2.836964,32762.0,82.740461,32393.052607,32395.0,...,147.768805,17.097932,192.394555,7.687587,1446.583756,0.054958,0.010931,0.386816,76.546463,0.006603
0,32263.0,32529.0,2.273938e+12,4.088103,142.0,2.852911,32762.0,82.664610,32393.482695,32396.0,...,147.374712,17.192164,192.831103,7.862021,1481.460545,0.056036,0.010980,0.386627,76.523969,0.006606
0,32265.6,32527.4,2.273964e+12,4.069119,140.0,2.850971,32762.0,81.822975,32393.674665,32395.0,...,149.059991,16.780017,192.798339,7.812183,1471.589294,0.055212,0.010724,0.383160,76.005966,0.006393
0,32263.6,32530.0,2.274130e+12,4.076701,141.0,2.855036,32762.0,82.008632,32394.853715,32397.0,...,148.328103,16.974712,193.961698,7.622058,1436.520074,0.054850,0.011077,0.380768,76.383426,0.006672
0,32265.0,32525.0,2.273825e+12,4.058286,136.5,2.887308,32762.0,80.665350,32392.684818,32395.0,...,150.541301,16.461099,191.391324,7.925704,1466.732349,0.056538,0.010445,0.373034,74.478313,0.005986
0,32264.0,32530.0,2.274161e+12,4.079378,140.0,2.852640,32728.0,81.752489,32395.071066,32396.0,...,148.421320,16.963420,194.257499,7.905399,1492.288879,0.056142,0.011021,0.384675,76.988267,0.006667
0,32262.0,32525.4,2.273692e+12,4.072814,139.5,2.852978,32762.0,81.883404,32391.733272,32394.0,...,148.915090,16.793693,190.700046,7.842640,1446.042916,0.056591,0.010637,0.387853,76.901289,0.006259
0,32262.0,32530.0,2.273992e+12,4.090385,142.0,2.847930,32762.0,82.747473,32393.869866,32395.0,...,147.020305,17.276013,193.159668,7.689432,1444.830180,0.055834,0.011264,0.387951,77.185143,0.006828
0,32265.6,32524.0,2.273763e+12,4.053863,136.5,2.893640,32762.0,80.478524,32392.242732,32394.0,...,151.146747,16.357852,190.861098,7.981080,1471.188740,0.056918,0.010409,0.381302,75.895393,0.006009

In [18]:
#calculate the CV of each feature
cv_TO = df_TO.std() / df_TO.mean()
cv_GE = df_GE.std() / df_GE.mean()

#Create a dataframe with the CV of each feature with the name of the column "CV"
cv_TO = pd.DataFrame(cv_TO, columns=['CV'])
cv_GE = pd.DataFrame(cv_GE, columns=['CV'])

#add column with the name of the feature
cv_TO['Feature'] = cv_TO.index
cv_GE['Feature'] = cv_GE.index

#change the index of the dataframe
cv_TO = cv_TO.reset_index(drop=True)
cv_GE = cv_GE.reset_index(drop=True)

#Add a column Manufacturer with the name of the manufacturer
cv_TO['Manufacturer'] = 'Toshiba'
cv_GE['Manufacturer'] = 'GE'

#concatenate the two dataframe
cv = pd.concat([cv_TO, cv_GE])

#reset the index
cv = cv.reset_index(drop=True)


cv

           CV                                            Feature Manufacturer
0    0.000045                   original_firstorder_10Percentile      Toshiba
1    0.000070                   original_firstorder_90Percentile      Toshiba
2    0.000072                         original_firstorder_Energy      Toshiba
3    0.002907                        original_firstorder_Entropy      Toshiba
4    0.013933             original_firstorder_InterquartileRange      Toshiba
..        ...                                                ...          ...
167  0.076259  original_gldm_LargeDependenceLowGrayLevelEmphasis           GE
168  0.083833                 original_gldm_LowGrayLevelEmphasis           GE
169  0.011336              original_gldm_SmallDependenceEmphasis           GE
170  0.055800  original_gldm_SmallDependenceHighGrayLevelEmph...           GE
171  0.101055  original_gldm_SmallDependenceLowGrayLevelEmphasis           GE

[172 rows x 3 columns]

In [19]:
#Get the features with CV > 0.10
cv_10 = cv[cv['CV'] > 0.10]

#reset the index
cv_10 = cv_10.reset_index(drop=True)

cv_10

         CV                                            Feature Manufacturer
0  0.606325                       original_firstorder_Skewness           GE
1  0.471656                         original_glcm_ClusterShade           GE
2  0.261450                          original_glcm_Correlation           GE
3  0.106563            original_glszm_LowGrayLevelZoneEmphasis           GE
4  0.115859       original_glszm_SmallAreaLowGrayLevelEmphasis           GE
5  0.101055  original_gldm_SmallDependenceLowGrayLevelEmphasis           GE

In [20]:
#Save the dataframe in a csv file
cv_10.to_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_repeatable/cv_Cyl0.csv', index=False)