In [ ]:
import pandas as pd
import pingouin as pg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import statsmodels.api as sm

In [11]:
# Loding the TO csv file
df1 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test1/rect0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test2/rect0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test3/rect0.csv")
df4 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test4/rect0.csv")
df5 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test5/rect0.csv")
df6 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test6/rect0.csv")
df7 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test7/rect0.csv")
df8 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test8/rect0.csv")
df9 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test9/rect0.csv")
df10 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Test10/rect0.csv")

# Concatenating the 10 csv files
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_TO = df
df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,31563.0,32852.0,2.943864e+12,6.055136,798.00,2.221000,33285.0,416.070282,32329.034446,32476.5,...,2062.553980,0.001276,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31560.5,32856.0,2.943389e+12,6.080577,775.25,2.265919,33322.0,413.322609,32326.435724,32470.0,...,1911.775797,0.001609,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31560.5,32865.0,2.945170e+12,6.076604,743.00,2.366861,33285.0,404.728516,32336.281250,32471.0,...,2116.572964,0.001318,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31578.0,32856.5,2.945200e+12,6.067487,768.75,2.329448,33285.0,408.958330,32336.457031,32478.5,...,2069.972914,0.001309,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31567.5,32869.0,2.945075e+12,6.080343,789.50,2.254610,33285.0,416.258165,32335.655185,32478.5,...,2092.793914,0.001365,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31562.0,32850.0,2.943517e+12,6.066885,776.50,2.265563,33333.0,412.870739,32327.164062,32475.0,...,2191.787280,0.001077,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31566.5,32867.0,2.944784e+12,6.065623,803.00,2.215266,33285.0,418.732406,32334.046165,32479.5,...,2078.594287,0.001332,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31556.5,32848.0,2.942679e+12,6.082705,769.25,2.280453,33333.0,413.299867,32322.535866,32466.0,...,2170.227510,0.001085,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31562.0,32876.0,2.946044e+12,6.086015,749.25,2.364888,33285.0,407.177426,32341.035866,32475.0,...,2135.023988,0.001380,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,31576.0,32848.5,2.944501e+12,6.065166,757.50,2.341785,33333.0,408.325456,32332.628906,32477.0,...,2196.865965,0.001076,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [12]:
# Loding the GE csv files and joining them in a single dataframe
df1 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test1/rect0.csv")
df2 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test2/rect0.csv")
df3 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test3/rect0.csv")
df4 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test4/rect0.csv")
df5 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test5/rect0.csv")
df6 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test6/rect0.csv")
df7 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test7/rect0.csv")
df8 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test8/rect0.csv")
df9 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test9/rect0.csv")
df10 = pd.read_csv("../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Test10/rect0.csv")

df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])

#Elimino le colonne diagnostics
string_to_match = 'diagnostics'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
string_to_match = 'Unnamed:'
filtered_columns = [col for col in df.columns if string_to_match not in col]
df = df[filtered_columns]
df_GE = df
df_GE

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,32768.0,34210.0,3.272638e+12,5.292096,1218.50,1.550485,34591.0,500.998444,33496.106310,33576.0,...,1075.761709,0.008712,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34205.5,3.272150e+12,5.290044,1221.50,1.519448,34591.0,504.907381,33493.586077,33568.0,...,1068.903842,0.009626,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34208.5,3.274184e+12,5.337770,1176.00,1.540494,34591.0,500.649224,33504.054870,33585.5,...,1089.466190,0.009522,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34198.5,3.273023e+12,5.296183,1199.50,1.547322,34591.0,499.663512,33498.114540,33581.0,...,1068.698156,0.009248,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34210.0,3.274369e+12,5.324335,1194.75,1.545627,34608.0,502.712877,33504.961248,33589.5,...,1092.118953,0.009236,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34196.0,3.272719e+12,5.307956,1176.00,1.557886,34591.0,494.530116,33496.632373,33576.0,...,1081.039361,0.008688,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34213.0,3.273726e+12,5.307522,1216.50,1.541825,34608.0,505.523886,33501.617627,33581.0,...,1097.262223,0.009003,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34197.0,3.271646e+12,5.282962,1212.50,1.527190,34591.0,500.848731,33491.069273,33566.5,...,1075.086086,0.009258,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34212.0,3.275212e+12,5.347991,1179.75,1.531185,34608.0,505.808233,33509.245885,33597.0,...,1116.158110,0.009642,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1
0,32768.0,34193.5,3.272527e+12,5.292584,1188.75,1.554732,34591.0,495.634357,33495.641289,33577.5,...,1086.442650,0.008838,RAD_GE_LUNG_7_FBP_1,GE MEDICAL SYSTEMS,1.25,"[0.703125, 0.703125]",LUNG,7,FBP,1

In [13]:
#Save the dataframe in a csv file
df_TO.to_csv('../../../../RadiomiK/Features_Positioning_test/TO_test/Final/Global/rect0_glob.csv', index=False)
df_GE.to_csv('../../../../RadiomiK/Features_Positioning_test/GE_test/Final/Global/rect0_glob.csv', index=False)

In [14]:
#add a column to the dataframe with the number of test that goes from 1 to 10
df_TO.insert(0, 'Test', range(1, 1 + len(df_TO)))
df_GE.insert(0, 'Test', range(1, 1 + len(df_GE)))

df_TO

,Test,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,...,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis,image_ID,Manufacturer,Slice Thickness,Pixel_Spacing,Kernel,Dose,ASIR,Num_Acquisition
0,1,31563.0,32852.0,2.943864e+12,6.055136,798.00,2.221000,33285.0,416.070282,32329.034446,...,2062.553980,0.001276,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,2,31560.5,32856.0,2.943389e+12,6.080577,775.25,2.265919,33322.0,413.322609,32326.435724,...,1911.775797,0.001609,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,3,31560.5,32865.0,2.945170e+12,6.076604,743.00,2.366861,33285.0,404.728516,32336.281250,...,2116.572964,0.001318,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,4,31578.0,32856.5,2.945200e+12,6.067487,768.75,2.329448,33285.0,408.958330,32336.457031,...,2069.972914,0.001309,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,5,31567.5,32869.0,2.945075e+12,6.080343,789.50,2.254610,33285.0,416.258165,32335.655185,...,2092.793914,0.001365,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,6,31562.0,32850.0,2.943517e+12,6.066885,776.50,2.265563,33333.0,412.870739,32327.164062,...,2191.787280,0.001077,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,7,31566.5,32867.0,2.944784e+12,6.065623,803.00,2.215266,33285.0,418.732406,32334.046165,...,2078.594287,0.001332,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,8,31556.5,32848.0,2.942679e+12,6.082705,769.25,2.280453,33333.0,413.299867,32322.535866,...,2170.227510,0.001085,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,9,31562.0,32876.0,2.946044e+12,6.086015,749.25,2.364888,33285.0,407.177426,32341.035866,...,2135.023988,0.001380,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1
0,10,31576.0,32848.5,2.944501e+12,6.065166,757.50,2.341785,33333.0,408.325456,32332.628906,...,2196.865965,0.001076,RAD_TO_LUNG_4_FBP_1,TOSHIBA,1,"[0.781, 0.781]",LUNG,4,FBP,1

In [15]:
#Keep only the [1,87] columns of the dataframe
df_TO = df_TO.iloc[:, 1:87]
df_GE = df_GE.iloc[:, 1:87]

df_TO

,original_firstorder_10Percentile,original_firstorder_90Percentile,original_firstorder_Energy,original_firstorder_Entropy,original_firstorder_InterquartileRange,original_firstorder_Kurtosis,original_firstorder_Maximum,original_firstorder_MeanAbsoluteDeviation,original_firstorder_Mean,original_firstorder_Median,...,original_gldm_GrayLevelNonUniformity,original_gldm_GrayLevelVariance,original_gldm_HighGrayLevelEmphasis,original_gldm_LargeDependenceEmphasis,original_gldm_LargeDependenceHighGrayLevelEmphasis,original_gldm_LargeDependenceLowGrayLevelEmphasis,original_gldm_LowGrayLevelEmphasis,original_gldm_SmallDependenceEmphasis,original_gldm_SmallDependenceHighGrayLevelEmphasis,original_gldm_SmallDependenceLowGrayLevelEmphasis
0,31563.0,32852.0,2.943864e+12,6.055136,798.00,2.221000,33285.0,416.070282,32329.034446,32476.5,...,49.650568,384.287950,3054.894531,2.748580,9052.829190,0.002889,0.001548,0.703072,2062.553980,0.001276
0,31560.5,32856.0,2.943389e+12,6.080577,775.25,2.265919,33322.0,413.322609,32326.435724,32470.0,...,48.429688,382.923256,2840.667259,2.751420,8479.466974,0.006291,0.002490,0.702173,1911.775797,0.001609
0,31560.5,32865.0,2.945170e+12,6.076604,743.00,2.366861,33285.0,404.728516,32336.281250,32471.0,...,48.363636,376.731461,3077.224077,2.639915,8790.449219,0.002791,0.001571,0.715931,2116.572964,0.001318
0,31578.0,32856.5,2.945200e+12,6.067487,768.75,2.329448,33285.0,408.958330,32336.457031,32478.5,...,49.455256,375.276406,3076.765625,2.861506,9420.865057,0.003091,0.001610,0.694977,2069.972914,0.001309
0,31567.5,32869.0,2.945075e+12,6.080343,789.50,2.254610,33285.0,416.258165,32335.655185,32478.5,...,48.579545,387.245425,3085.745384,2.741477,9041.561435,0.002945,0.001627,0.704100,2092.793914,0.001365
0,31562.0,32850.0,2.943517e+12,6.066885,776.50,2.265563,33333.0,412.870739,32327.164062,32475.0,...,49.216619,380.586420,3253.637784,2.805398,9817.851562,0.002150,0.001243,0.701539,2191.787280,0.001077
0,31566.5,32867.0,2.944784e+12,6.065623,803.00,2.215266,33285.0,418.732406,32334.046165,32479.5,...,49.279119,388.706813,3080.385653,2.732955,8995.949574,0.002942,0.001601,0.702472,2078.594287,0.001332
0,31556.5,32848.0,2.942679e+12,6.082705,769.25,2.280453,33333.0,413.299867,32322.535866,32466.0,...,48.623580,382.809146,3236.174716,2.794744,9782.499290,0.002206,0.001263,0.700836,2170.227510,0.001085
0,31562.0,32876.0,2.946044e+12,6.086015,749.25,2.364888,33285.0,407.177426,32341.035866,32475.0,...,48.098722,381.203157,3101.848011,2.612926,8719.530540,0.002847,0.001632,0.714573,2135.023988,0.001380
0,31576.0,32848.5,2.944501e+12,6.065166,757.50,2.341785,33333.0,408.325456,32332.628906,32477.0,...,49.745739,373.833451,3270.344815,2.906250,10184.295099,0.002250,0.001259,0.695259,2196.865965,0.001076

In [16]:
#calculate the CV of each feature
cv_TO = df_TO.std() / df_TO.mean()
cv_GE = df_GE.std() / df_GE.mean()

#Create a dataframe with the CV of each feature with the name of the column "CV"
cv_TO = pd.DataFrame(cv_TO, columns=['CV'])
cv_GE = pd.DataFrame(cv_GE, columns=['CV'])

#add column with the name of the feature
cv_TO['Feature'] = cv_TO.index
cv_GE['Feature'] = cv_GE.index

#change the index of the dataframe
cv_TO = cv_TO.reset_index(drop=True)
cv_GE = cv_GE.reset_index(drop=True)

#Add a column Manufacturer with the name of the manufacturer
cv_TO['Manufacturer'] = 'Toshiba'
cv_GE['Manufacturer'] = 'GE'

#concatenate the two dataframe
cv = pd.concat([cv_TO, cv_GE])

#reset the index
cv = cv.reset_index(drop=True)


cv

           CV                                            Feature Manufacturer
0    0.000220                   original_firstorder_10Percentile      Toshiba
1    0.000298                   original_firstorder_90Percentile      Toshiba
2    0.000351                         original_firstorder_Energy      Toshiba
3    0.001637                        original_firstorder_Entropy      Toshiba
4    0.025697             original_firstorder_InterquartileRange      Toshiba
..        ...                                                ...          ...
167  0.030750  original_gldm_LargeDependenceLowGrayLevelEmphasis           GE
168  0.019021                 original_gldm_LowGrayLevelEmphasis           GE
169  0.009208              original_gldm_SmallDependenceEmphasis           GE
170  0.013453  original_gldm_SmallDependenceHighGrayLevelEmph...           GE
171  0.038998  original_gldm_SmallDependenceLowGrayLevelEmphasis           GE

[172 rows x 3 columns]

In [17]:
#Get the features with CV > 0.10
cv_10 = cv[cv['CV'] > 0.10]

#reset the index
cv_10 = cv_10.reset_index(drop=True)

cv_10

         CV                                            Feature Manufacturer
0  0.234430         original_glrlm_LongRunLowGrayLevelEmphasis      Toshiba
1  0.221238             original_glrlm_LowGrayLevelRunEmphasis      Toshiba
2  0.217762        original_glrlm_ShortRunLowGrayLevelEmphasis      Toshiba
3  0.302734       original_glszm_LargeAreaLowGrayLevelEmphasis      Toshiba
4  0.163169            original_glszm_LowGrayLevelZoneEmphasis      Toshiba
5  0.110214       original_glszm_SmallAreaLowGrayLevelEmphasis      Toshiba
6  0.392656  original_gldm_LargeDependenceLowGrayLevelEmphasis      Toshiba
7  0.225903                 original_gldm_LowGrayLevelEmphasis      Toshiba
8  0.130259  original_gldm_SmallDependenceLowGrayLevelEmphasis      Toshiba

In [18]:
#Save the dataframe in a csv file
cv_10.to_csv('../../../../RadiomiK/Features_Positioning_test/Features_Not_repeatable/cv_Rect0.csv', index=False)